language: node_js
node_js: 9
after_success:
- yarn coveralls
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: fV9xUOgW3/5bvCakH1LBSNio4NzCWG4cqf5v6qmbFKJhP9FVBpCz1Krepl8eHP/dpoKIVTzfFi1b1F009IzqeEChtnybcEXUxpkyKSgSGd/qJBuZFGz9ZyMRZfZ66QZvebmhGQtgo5Gf5+wUUo38ZYYvir1yQGo65S9y+oYOHkUtCK4SpK6Aj/TPwJYCGQfvzSg2mpHlFgN1yOSD3/VUEjAuxFlCq1DvBgOR234FRSbQ2lPubOmqf8kxvkG5Kay9VatyiGml2V1oFwjq7PgbMRzzGOIn9H6TCY372zPN+iPevjSA4jKMw4Kn48UlGZlWx40Kf/A835A5Q7EvtK6bdnc8jWmvxvzAVu1RhQeBnebqG/W2MIVewouLn9bmUDNCx5X45Qi+q2mcUt/KYZmRdZrOUIljVyep7VkEqX8GJmqugw/NFYa2AN2olh8WZafBqc/fRtLztyidnT269aowldq81Ms08vAaEpsGBODFSZBJT6i5jkchPssObo09d65+kWAKXlOWmjXSN26I5D/BV9yYFTVN9h3FFoOzJ0o0PE+Dxenz6tbS5g70nz1rO+1qict5K70jEuDb5rXgeBXS9JhQCYhcEsI6I5VFJLtCz73+0m2FX/Zs0tQVvG44TTNDpYWZUg9Q14TrKBtE1HyVGwCRJMV6ErWgdaaR4knmLYk=
cache: yarn
